analyzer:
  errors:
    eol_at_end_of_file: ignore
    lines_longer_than_80_chars: ignore
    cascade_invocations: ignore
    public_member_api_docs: ignore
# include: package:flutter_lints/flutter.yaml
include: package:lints/recommended.yaml
# include: package:lint/strict.yaml
# include: package:lint/casual.yaml
# include: package:very_good_analysis/analysis_options.yaml
