// Mocks generated by Mockito 5.4.6 from annotations
// in numpang_app/test/presentation/bloc/search_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:latlong2/latlong.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:numpang_app/core/errors/failures.dart' as _i5;
import 'package:numpang_app/domain/entities/place_suggestion.dart' as _i7;
import 'package:numpang_app/domain/repositories/geocoding_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GeocodingRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockGeocodingRepository extends _i1.Mock
    implements _i3.GeocodingRepository {
  MockGeocodingRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.LatLng>> searchAddress(
    String? query,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#searchAddress, [query]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.LatLng>>.value(
              _FakeEither_0<_i5.Failure, _i6.LatLng>(
                this,
                Invocation.method(#searchAddress, [query]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.LatLng>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, String>> reverseGeocode(
    _i6.LatLng? position,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#reverseGeocode, [position]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, String>>.value(
              _FakeEither_0<_i5.Failure, String>(
                this,
                Invocation.method(#reverseGeocode, [position]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, String>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i7.PlaceSuggestion>>> autocomplete(
    String? input,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#autocomplete, [input]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i7.PlaceSuggestion>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i7.PlaceSuggestion>>(
                    this,
                    Invocation.method(#autocomplete, [input]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i7.PlaceSuggestion>>>);
}
